// ------------------------------------------------------------
// GUIDES PRATIQUES du site public (référencement : répondent aux questions que les commerçants tapent dans Google).
// Chaque guide existe en français et en anglais : { fr: {...}, en: {...} } avec ses propres adresses.
// Pour en ajouter un : une entrée ici, c'est tout (pages, plan du site, liens croisés et hreflang suivent).
// ------------------------------------------------------------
export const DATE_GUIDES = '2026-10-05';

// modele : fichier Excel gratuit lié au guide (public/modeles/, voir scripts/modeles.mjs)
import { GUIDES_PAYS } from './guides-pays.js';

const GUIDES_BASE = [
  {
    cle: 'inventaire',
    modele: 'inventaire',
    metier: '/gestion-stock/',
    fr: {
      slug: 'faire-un-inventaire-de-stock',
      titre: 'Comment faire un inventaire de stock, étape par étape',
      court: 'Faire un inventaire de stock',
      description: 'Méthode simple pour faire l’inventaire de votre commerce : préparation, comptage, écarts, valeur du stock. Avec un modèle Excel gratuit à télécharger.',
      chapo: 'L’inventaire consiste à compter ce que vous avez réellement en rayon et en réserve, puis à le comparer avec ce que votre cahier ou votre logiciel annonce. Bien fait, il révèle les pertes, évite les ruptures et vous dit ce que votre stock vaut.',
      sections: [
        { h: 'Pourquoi faire un inventaire régulièrement', p: ['Un stock que l’on ne compte jamais finit toujours par différer de la réalité : vols, casse, erreurs de rendu, produits périmés, ventes non notées. Plus l’inventaire est espacé, plus l’écart est grand et plus il est difficile d’en trouver la cause.', 'Un inventaire complet une à deux fois par an est un minimum. Pour les produits qui coûtent cher ou qui partent vite, un comptage tournant chaque semaine est bien plus efficace.'] },
        { h: 'Préparer l’inventaire', p: ['Choisissez un moment calme : avant l’ouverture, ou après la fermeture. Arrêtez les entrées et les sorties de marchandise pendant le comptage, ou notez-les à part.', 'Rangez les articles par famille, mettez les produits identiques ensemble et prévoyez une liste imprimée ou un fichier avec le nom de chaque article, son unité (pièce, kg, litre, carton) et la quantité attendue.'] },
        { h: 'Compter, étape par étape', l: ['Comptez zone par zone (rayon 1, rayon 2, réserve) et cochez chaque zone terminée.', 'Notez la quantité réellement trouvée, jamais celle que vous croyez avoir.', 'Faites compter par deux personnes les articles de grande valeur.', 'Séparez les produits abîmés ou périmés : ils ne comptent pas dans le stock vendable.', 'Recomptez immédiatement tout écart important avant de le valider.'] },
        { h: 'Calculer les écarts et la valeur du stock', p: ['L’écart est la quantité comptée moins la quantité attendue. Un écart négatif signale une perte ; un écart positif, une entrée non notée ou une erreur de comptage.', 'La valeur du stock se calcule article par article : quantité × prix d’achat. Additionnez le tout pour savoir combien d’argent est immobilisé en marchandise. C’est aussi la base pour calculer vos marges.'] },
        { h: 'Faire l’inventaire avec Kaislo', p: ['Dans Kaislo, ouvrez Stock, touchez l’article et indiquez la quantité comptée : le stock est corrigé et l’écart est gardé dans l’historique. Vous voyez la valeur du stock au prix d’achat et à la vente, et vous pouvez exporter l’inventaire en Excel à tout moment.'] },
      ],
      faq: [
        ['À quelle fréquence faire un inventaire ?', 'Un inventaire complet au moins une fois par an, et un comptage tournant (quelques familles chaque semaine) pour les produits chers ou qui se vendent beaucoup.'],
        ['Que faire d’un écart d’inventaire ?', 'Recomptez, cherchez une entrée ou une vente non notée, puis corrigez le stock et gardez la trace de l’écart pour comprendre sa cause.'],
        ['Peut-on faire l’inventaire sans logiciel ?', 'Oui, avec un cahier ou un tableau Excel, par exemple le modèle gratuit proposé sur cette page. Un logiciel évite de tout recopier et met le stock à jour à chaque vente.'],
      ],
    },
    en: {
      slug: 'how-to-do-a-stock-inventory',
      titre: 'How to do a stock inventory, step by step',
      court: 'Doing a stock inventory',
      description: 'A simple method to take inventory in your shop: preparation, counting, discrepancies and stock value. Includes a free Excel template to download.',
      chapo: 'A stock inventory means counting what you really have on the shelves and in the storeroom, then comparing it with what your notebook or software says. Done well, it reveals losses, prevents stock-outs and tells you what your stock is worth.',
      sections: [
        { h: 'Why take inventory regularly', p: ['Stock that is never counted always drifts away from reality: theft, breakage, change errors, expired goods, sales that were not recorded. The longer you wait, the bigger the gap and the harder it is to find the cause.', 'A full inventory once or twice a year is the minimum. For expensive or fast-moving items, a rolling weekly count is far more effective.'] },
        { h: 'Prepare the inventory', p: ['Pick a quiet moment: before opening or after closing. Stop goods coming in and going out during the count, or note them separately.', 'Group items by family, keep identical products together and prepare a printed list or a file with each item’s name, its unit (piece, kg, litre, carton) and the expected quantity.'] },
        { h: 'Count, step by step', l: ['Count zone by zone (shelf 1, shelf 2, storeroom) and tick each finished zone.', 'Write down the quantity actually found, never the one you think you have.', 'Have two people count high-value items.', 'Set aside damaged or expired products: they are not sellable stock.', 'Recount any large discrepancy straight away before confirming it.'] },
        { h: 'Work out discrepancies and stock value', p: ['The discrepancy is the counted quantity minus the expected quantity. A negative gap points to a loss; a positive gap, to an unrecorded delivery or a counting mistake.', 'Stock value is calculated item by item: quantity × purchase price. Add it all up to see how much money is tied up in goods. It is also the basis for calculating your margins.'] },
        { h: 'Take inventory with Kaislo', p: ['In Kaislo, open Stock, tap the item and enter the counted quantity: the stock is corrected and the difference is kept in the history. You see the stock value at purchase and selling price, and you can export the inventory to Excel at any time.'] },
      ],
      faq: [
        ['How often should you take inventory?', 'A full inventory at least once a year, plus a rolling count (a few families each week) for expensive or fast-selling products.'],
        ['What should you do about an inventory discrepancy?', 'Recount, look for an unrecorded delivery or sale, then correct the stock and keep a record of the gap to understand its cause.'],
        ['Can you take inventory without software?', 'Yes, with a notebook or an Excel sheet, for example the free template on this page. Software saves rewriting everything and updates stock with every sale.'],
      ],
    },
  },
  {
    cle: 'marge',
    modele: 'ventes',
    metier: '/gestion-boutique/',
    fr: {
      slug: 'calculer-sa-marge-commerciale',
      seo: 'Calculer sa marge commerciale et fixer ses prix',
      titre: 'Calculer sa marge commerciale et fixer ses prix de vente',
      court: 'Calculer sa marge',
      description: 'Comment calculer la marge, le taux de marge et le prix de vente d’un produit, avec des exemples en FCFA, dirhams ou euros. Simple et sans jargon.',
      chapo: 'Beaucoup de commerçants savent combien ils vendent, peu savent combien ils gagnent vraiment. La marge, c’est la différence entre le prix de vente et le prix d’achat : elle paie votre loyer, vos salaires et votre revenu.',
      sections: [
        { h: 'La formule de la marge', p: ['Marge = prix de vente − prix d’achat. Si vous achetez un sac de riz 12 000 et le vendez 15 000, votre marge est de 3 000 par sac.', 'Le taux de marge compare cette marge au prix d’achat : 3 000 ÷ 12 000 = 25 %. Le taux de marque la compare au prix de vente : 3 000 ÷ 15 000 = 20 %. Choisissez l’un des deux et gardez-le toujours.'] },
        { h: 'Calculer son prix de vente', p: ['Pour viser un taux de marge de 30 %, multipliez le prix d’achat par 1,30. Pour viser un taux de marque de 30 %, divisez-le par 0,70. Arrondissez ensuite à un prix qui plaît au client, mais sans descendre sous votre marge minimale.'] },
        { h: 'Ce que la marge doit couvrir', l: ['Le loyer, l’électricité et l’eau.', 'Les salaires et le transport.', 'Les pertes : casse, vol, produits périmés.', 'Vos remises et le crédit non remboursé.', 'Et enfin, votre propre revenu.'] },
        { h: 'Les erreurs fréquentes', p: ['Oublier les frais de transport dans le prix d’achat, garder un ancien prix d’achat alors que le fournisseur a augmenté, ou accorder des remises sans savoir ce qu’il reste. Mettez à jour vos prix d’achat à chaque livraison.'] },
        { h: 'Suivre ses marges avec Kaislo', p: ['Renseignez le prix d’achat de chaque article : Kaislo calcule la marge sur chaque vente, par article et sur la période, et affiche le taux de marge dans le tableau de bord et dans le rapport Excel ou PDF.'] },
      ],
      faq: [
        ['Quelle est la différence entre taux de marge et taux de marque ?', 'Le taux de marge se calcule sur le prix d’achat, le taux de marque sur le prix de vente. Le second est toujours plus petit pour la même marge.'],
        ['Quelle marge viser pour une épicerie ?', 'Cela dépend des produits : faible sur les produits de base très comparés, plus élevée sur les produits d’appoint. Calculez la marge moyenne réelle plutôt qu’un chiffre unique.'],
      ],
    },
    en: {
      slug: 'how-to-calculate-profit-margin',
      seo: 'Calculate profit margin and set selling prices',
      titre: 'How to calculate profit margin and set your selling prices',
      court: 'Calculating margin',
      description: 'How to calculate margin, markup and selling price for a product, with examples in CFA francs, dirhams or euros. Simple and jargon-free.',
      chapo: 'Many shopkeepers know how much they sell, few know how much they really earn. Margin is the difference between selling price and purchase price: it pays your rent, your staff and your own income.',
      sections: [
        { h: 'The margin formula', p: ['Margin = selling price − purchase price. If you buy a bag of rice for 12,000 and sell it for 15,000, your margin is 3,000 per bag.', 'Markup compares that margin with the purchase price: 3,000 ÷ 12,000 = 25%. Margin rate compares it with the selling price: 3,000 ÷ 15,000 = 20%. Pick one and always stick with it.'] },
        { h: 'Work out your selling price', p: ['To aim for a 30% markup, multiply the purchase price by 1.30. To aim for a 30% margin rate, divide it by 0.70. Then round to a price customers like, without going below your minimum margin.'] },
        { h: 'What your margin has to cover', l: ['Rent, electricity and water.', 'Salaries and transport.', 'Losses: breakage, theft, expired goods.', 'Your discounts and unpaid credit.', 'And finally, your own income.'] },
        { h: 'Common mistakes', p: ['Forgetting transport costs in the purchase price, keeping an old purchase price after your supplier raised theirs, or giving discounts without knowing what is left. Update your purchase prices with every delivery.'] },
        { h: 'Track your margins with Kaislo', p: ['Enter each item’s purchase price: Kaislo calculates the margin on every sale, by item and over the period, and shows the margin rate on the dashboard and in the Excel or PDF report.'] },
      ],
      faq: [
        ['What is the difference between markup and margin rate?', 'Markup is calculated on the purchase price, margin rate on the selling price. The margin rate is always smaller for the same profit.'],
        ['What margin should a grocery store aim for?', 'It depends on the products: low on staples that customers compare, higher on convenience items. Calculate your real average margin rather than one fixed figure.'],
      ],
    },
  },
  {
    cle: 'credit',
    modele: 'ventes',
    metier: '/gestion-epicerie/',
    fr: {
      slug: 'gerer-le-credit-clients',
      titre: 'Gérer le crédit de ses clients sans perdre d’argent',
      court: 'Gérer le crédit clients',
      description: 'Comment accorder du crédit à vos clients, le suivre dans un carnet, relancer sans froisser et limiter les impayés. Conseils pratiques pour commerçants.',
      chapo: 'Le crédit fidélise, mais un carnet mal tenu mange votre trésorerie. L’objectif n’est pas de refuser le crédit, c’est de savoir à tout moment qui vous doit quoi, et depuis quand.',
      sections: [
        { h: 'Poser des règles claires', l: ['Ne faites crédit qu’à des clients que vous connaissez.', 'Fixez un plafond par client, adapté à ce qu’il peut rembourser.', 'Décidez d’un délai (une semaine, la fin du mois) et dites-le dès le départ.', 'Interdisez un nouveau crédit tant qu’un ancien dépasse le délai.'] },
        { h: 'Tenir un carnet fiable', p: ['Chaque vente à crédit doit être notée au moment de la vente : nom du client, date, articles, montant. Chaque remboursement l’est aussi, avec le mode de paiement. Un solde exact se calcule alors tout seul : achats à crédit moins remboursements.', 'Un carnet papier se perd et se discute. Un carnet numérique garde l’historique et peut être montré au client.'] },
        { h: 'Relancer sans froisser', p: ['Rappelez le montant et la date plutôt que de réclamer : « Votre solde est de 4 500 depuis le 12, souhaitez-vous passer le régler cette semaine ? ». Un message WhatsApp poli, envoyé tôt, vaut mieux qu’une demande gênante trois mois plus tard.'] },
        { h: 'Le crédit n’est pas de l’argent reçu', p: ['Dans vos comptes du soir, une vente à crédit compte dans le chiffre d’affaires mais pas dans l’argent en caisse. Ne dépensez que ce que vous avez reçu, et suivez le total dû comme un stock d’argent à récupérer.'] },
        { h: 'Le carnet de crédit de Kaislo', p: ['Kaislo garde le carnet de chaque client : achats à crédit, remboursements partiels ou totaux, solde dû et reçu de remboursement. Le rapport Excel liste tous les clients qui vous doivent de l’argent.'] },
      ],
      faq: [
        ['Comment limiter les impayés ?', 'Plafonnez le crédit par client, fixez un délai, notez chaque vente à crédit immédiatement et relancez dès le premier retard.'],
        ['Le crédit compte-t-il dans le chiffre d’affaires ?', 'Oui, la vente est faite, mais ce n’est pas de l’argent reçu tant que le client n’a pas remboursé.'],
      ],
    },
    en: {
      slug: 'manage-customer-credit',
      titre: 'How to manage customer credit without losing money',
      court: 'Managing customer credit',
      description: 'How to give customers credit, track it in a book, send reminders politely and limit unpaid debts. Practical advice for shopkeepers.',
      chapo: 'Credit builds loyalty, but a badly kept book eats your cash. The goal is not to refuse credit, it is to know at any time who owes you what, and since when.',
      sections: [
        { h: 'Set clear rules', l: ['Only give credit to customers you know.', 'Set a limit per customer, based on what they can repay.', 'Decide on a deadline (one week, end of month) and say so from the start.', 'No new credit while an old one is overdue.'] },
        { h: 'Keep a reliable book', p: ['Every credit sale must be written down at the time: customer name, date, items, amount. Every repayment too, with the payment method. An exact balance then calculates itself: credit purchases minus repayments.', 'A paper book gets lost and disputed. A digital book keeps the history and can be shown to the customer.'] },
        { h: 'Remind without offending', p: ['Mention the amount and the date rather than demanding: “Your balance has been 4,500 since the 12th, could you drop by this week to settle it?” A polite WhatsApp message sent early beats an awkward request three months later.'] },
        { h: 'Credit is not money received', p: ['In your evening accounts, a credit sale counts in revenue but not in cash. Only spend what you have received, and track the total owed like a stock of money to recover.'] },
        { h: 'Kaislo’s credit book', p: ['Kaislo keeps each customer’s book: credit purchases, partial or full repayments, balance owed and repayment receipt. The Excel report lists every customer who owes you money.'] },
      ],
      faq: [
        ['How do you limit unpaid debts?', 'Cap credit per customer, set a deadline, record every credit sale immediately and send a reminder at the first delay.'],
        ['Does credit count in revenue?', 'Yes, the sale is made, but it is not money received until the customer repays.'],
      ],
    },
  },
  {
    cle: 'cloture',
    modele: 'ventes',
    metier: '/gestion-restaurant/',
    fr: {
      slug: 'cloture-de-caisse-quotidienne',
      titre: 'La clôture de caisse : faire ses comptes chaque soir',
      court: 'Clôture de caisse',
      description: 'Comment faire la clôture de caisse de fin de journée : fond de caisse, total vendu, espèces, mobile money, écart. Méthode simple et modèle Excel gratuit.',
      chapo: 'Chaque soir, vous devez pouvoir répondre à deux questions : combien ai-je vendu, et l’argent qui devrait être là y est-il ? C’est le rôle de la clôture de caisse.',
      sections: [
        { h: 'Ouvrir la journée avec un fond de caisse', p: ['Comptez l’argent en caisse avant la première vente et notez-le : c’est le fond de caisse. Il sert à rendre la monnaie et doit être retrouvé le lendemain.'] },
        { h: 'Faire la clôture le soir', l: ['Relevez le total vendu de la journée.', 'Séparez par mode de paiement : espèces, Wave, Orange Money, carte, crédit.', 'Comptez les espèces réellement en caisse.', 'Calculez l’espèce attendue : fond de caisse + ventes en espèces + remboursements reçus − dépenses payées en espèces.', 'Comparez : la différence est l’écart de caisse.'] },
        { h: 'Comprendre l’écart', p: ['Un petit écart arrive (erreur de monnaie). Un écart qui revient chaque jour doit être expliqué : oubli de noter une vente ou une dépense, erreur de rendu, ou vol. Plus vous clôturez tôt après la fermeture, plus il est facile de retrouver la cause.'] },
        { h: 'Séparer ventes, argent reçu et crédit', p: ['Le total vendu inclut le crédit ; l’argent reçu ne l’inclut pas. Pour le mobile money, comparez avec le solde ou le relevé du compte. Kaislo n’encaisse jamais votre argent : il note comment vos clients vous ont payé.'] },
        { h: 'La fermeture de la journée avec Kaislo', p: ['Kaislo calcule le total vendu, l’argent par mode de paiement et l’espèce attendue ; vous indiquez l’espèce comptée et l’écart s’affiche. Le ticket de clôture peut être imprimé ou gardé, et chaque journée apparaît dans le rapport Excel.'] },
      ],
      faq: [
        ['Qu’est-ce qu’un fond de caisse ?', 'La somme en espèces laissée dans la caisse à l’ouverture pour rendre la monnaie.'],
        ['Que faire si la caisse ne tombe pas juste ?', 'Recomptez, vérifiez les ventes, dépenses et remboursements de la journée, puis notez l’écart et surveillez s’il se répète.'],
      ],
    },
    en: {
      slug: 'daily-cash-closing',
      titre: 'Cash closing: doing your accounts every evening',
      court: 'Daily cash closing',
      description: 'How to close the till at the end of the day: float, total sales, cash, mobile money, difference. A simple method and a free Excel template.',
      chapo: 'Every evening you should be able to answer two questions: how much did I sell, and is the money that should be here actually here? That is what closing the till is for.',
      sections: [
        { h: 'Open the day with a cash float', p: ['Count the money in the till before the first sale and write it down: that is the float. It is used to give change and should be found again the next day.'] },
        { h: 'Close the till in the evening', l: ['Take the day’s total sales.', 'Split by payment method: cash, Wave, Orange Money, card, credit.', 'Count the cash actually in the till.', 'Work out expected cash: float + cash sales + repayments received − cash expenses paid.', 'Compare: the difference is the cash gap.'] },
        { h: 'Understand the gap', p: ['A small gap happens (change error). A gap that comes back every day must be explained: a sale or expense not recorded, a change error, or theft. The sooner you close after shutting, the easier it is to find the cause.'] },
        { h: 'Separate sales, money received and credit', p: ['Total sales include credit; money received does not. For mobile money, compare with the account balance or statement. Kaislo never collects your money: it records how your customers paid you.'] },
        { h: 'Day closing with Kaislo', p: ['Kaislo calculates total sales, money by payment method and expected cash; you enter the cash counted and the gap appears. The closing receipt can be printed or kept, and every day shows up in the Excel report.'] },
      ],
      faq: [
        ['What is a cash float?', 'The cash left in the till at opening to give change.'],
        ['What if the till does not balance?', 'Recount, check the day’s sales, expenses and repayments, then note the gap and watch whether it repeats.'],
      ],
    },
  },
  {
    cle: 'pertes',
    modele: 'inventaire',
    metier: '/gestion-stock/',
    fr: {
      slug: 'reduire-les-pertes-de-stock',
      seo: 'Réduire les pertes de stock : casse, vol, péremption',
      titre: 'Réduire les pertes de stock : casse, vol, produits périmés',
      court: 'Réduire les pertes de stock',
      description: 'Les causes des pertes de stock dans un commerce et des moyens concrets de les réduire : rotation, alertes, droits des vendeurs, inventaires réguliers.',
      chapo: 'Dans un commerce, chaque produit perdu est du bénéfice qui disparaît. Casse, péremption, vols, erreurs : on ne peut pas tout supprimer, mais on peut les voir, les mesurer et les réduire.',
      sections: [
        { h: 'Où partent les pertes', l: ['Produits périmés ou abîmés avant d’être vendus.', 'Vols de clients ou d’employés.', 'Erreurs de rendu de monnaie ou de pesée.', 'Ventes non enregistrées.', 'Sur-stock qui immobilise l’argent et vieillit.'] },
        { h: 'Appliquer le premier entré, premier sorti', p: ['Placez les produits les plus anciens devant et vendez-les en premier. Indiquez la date de péremption sur les produits sensibles et vérifiez-la chaque semaine.'] },
        { h: 'Commander juste', p: ['Fixez un seuil d’alerte par article : quand le stock descend sous ce seuil, vous commandez. Le seuil dépend de la vitesse de vente et du délai de livraison de votre fournisseur. Évitez de commander « au cas où » : un sur-stock coûte cher.'] },
        { h: 'Contrôler sans fliquer', p: ['Donnez à chaque vendeur son propre accès avec un code PIN. Chaque vente, remise et annulation est alors attachée à une personne, avec un motif. Réservez les remises et les corrections de stock au gérant ou aux personnes de confiance.'] },
        { h: 'Mesurer avec des inventaires fréquents', p: ['Un comptage tournant hebdomadaire sur les articles chers repère un problème en quelques jours au lieu de quelques mois. Kaislo garde l’historique des mouvements et des écarts, et signale les articles en rupture ou bientôt en rupture.'] },
      ],
      faq: [
        ['Comment réduire les produits périmés ?', 'Vendez les plus anciens d’abord, surveillez les dates chaque semaine et commandez des quantités adaptées à votre vitesse de vente.'],
        ['Comment repérer un vol ?', 'Comparez régulièrement stock attendu et stock compté, et attachez chaque vente et annulation à un vendeur identifié.'],
      ],
    },
    en: {
      slug: 'reduce-stock-losses',
      seo: 'Reduce stock losses: breakage, theft, expiry',
      titre: 'Reducing stock losses: breakage, theft and expired goods',
      court: 'Reducing stock losses',
      description: 'The causes of stock loss in a shop and practical ways to reduce it: rotation, alerts, seller permissions and regular inventory counts.',
      chapo: 'In a shop, every lost product is profit that disappears. Breakage, expiry, theft, mistakes: you cannot remove them all, but you can see them, measure them and reduce them.',
      sections: [
        { h: 'Where losses come from', l: ['Products that expire or get damaged before being sold.', 'Theft by customers or staff.', 'Errors in change or weighing.', 'Sales that were not recorded.', 'Overstock that ties up money and ages.'] },
        { h: 'Apply first in, first out', p: ['Put the oldest products at the front and sell them first. Show the expiry date on sensitive products and check it every week.'] },
        { h: 'Order just enough', p: ['Set an alert threshold per item: when stock falls below it, you reorder. The threshold depends on how fast it sells and your supplier’s delivery time. Avoid ordering “just in case”: overstock is expensive.'] },
        { h: 'Control without policing', p: ['Give each seller their own access with a PIN. Every sale, discount and cancellation is then tied to a person, with a reason. Keep discounts and stock corrections for the manager or trusted people.'] },
        { h: 'Measure with frequent counts', p: ['A weekly rolling count of expensive items spots a problem in days instead of months. Kaislo keeps the history of movements and discrepancies, and flags items out of stock or about to run out.'] },
      ],
      faq: [
        ['How do you reduce expired products?', 'Sell the oldest first, check dates every week and order quantities that match how fast you sell.'],
        ['How do you spot theft?', 'Regularly compare expected and counted stock, and tie every sale and cancellation to an identified seller.'],
      ],
    },
  },
  {
    cle: 'mobile-money',
    modele: 'ventes',
    metier: '/gestion-boutique/',
    fr: {
      slug: 'noter-les-paiements-mobile-money',
      seo: 'Mobile money en boutique : noter Wave et Orange Money',
      titre: 'Mobile money en boutique : noter Wave et Orange Money sans se tromper',
      court: 'Noter le mobile money',
      description: 'Comment suivre les paiements Wave, Orange Money, MTN ou M-Pesa dans votre commerce et rapprocher vos ventes avec le solde de votre compte.',
      chapo: 'Le mobile money s’est imposé dans les boutiques, mais il complique les comptes : l’argent n’est pas dans la caisse. Voici comment le noter proprement et vérifier qu’il ne manque rien.',
      sections: [
        { h: 'Le problème : l’argent n’est pas dans le tiroir', p: ['Quand un client paie par Wave, Orange Money, MTN MoMo ou M-Pesa, l’argent arrive directement sur votre téléphone. Si vous ne notez pas la vente avec ce mode de paiement, votre caisse en espèces paraît juste mais vos comptes sont faux.'] },
        { h: 'Noter chaque vente avec son mode de paiement', p: ['Enregistrez chaque vente avec le bon mode : espèces, Wave, Orange Money, carte… En fin de journée vous obtenez le total par mode, indispensable pour savoir ce que vous devez retrouver dans chaque « poche ».'] },
        { h: 'Rapprocher avec votre compte', l: ['Relevez le total mobile money de la journée dans vos comptes.', 'Comparez-le avec les entrées de votre application mobile money.', 'Cherchez les écarts : frais de retrait, paiement non noté, erreur de montant.', 'Gardez le relevé du mois pour votre comptable.'] },
        { h: 'Les frais et retraits', p: ['Les frais de retrait ou de transfert sont une dépense : notez-les comme telle pour ne pas gonfler votre bénéfice. Votre solde en mobile money fait partie de votre trésorerie au même titre que la caisse.'] },
        { h: 'Avec Kaislo', p: ['Kaislo propose les modes de paiement de votre pays (Wave, Orange Money, MTN, M-Pesa, carte…). Les comptes du soir et le rapport Excel détaillent l’argent reçu par mode. Kaislo n’encaisse jamais l’argent : il garde seulement la trace de la façon dont vos clients vous ont payé.'] },
      ],
      faq: [
        ['Kaislo encaisse-t-il les paiements mobile money ?', 'Non. Vos clients vous paient comme d’habitude ; Kaislo note le mode de paiement pour vos comptes.'],
        ['Comment vérifier que mon mobile money est juste ?', 'Comparez le total du mode dans vos comptes du soir avec les entrées de votre application, en tenant compte des frais.'],
      ],
    },
    en: {
      slug: 'record-mobile-money-payments',
      seo: 'Record mobile money payments in your shop',
      titre: 'Mobile money in your shop: recording Wave and Orange Money correctly',
      court: 'Recording mobile money',
      description: 'How to track Wave, Orange Money, MTN or M-Pesa payments in your business and reconcile your sales with your account balance.',
      chapo: 'Mobile money has taken over in shops, but it complicates your accounts: the money is not in the till. Here is how to record it properly and check nothing is missing.',
      sections: [
        { h: 'The problem: the money is not in the drawer', p: ['When a customer pays by Wave, Orange Money, MTN MoMo or M-Pesa, the money lands straight on your phone. If you do not record the sale with that payment method, your cash drawer looks right but your accounts are wrong.'] },
        { h: 'Record every sale with its payment method', p: ['Record each sale with the right method: cash, Wave, Orange Money, card… At the end of the day you get the total per method, essential to know what you should find in each “pocket”.'] },
        { h: 'Reconcile with your account', l: ['Take the day’s mobile money total from your accounts.', 'Compare it with the credits in your mobile money app.', 'Look for gaps: withdrawal fees, unrecorded payment, wrong amount.', 'Keep the month’s statement for your accountant.'] },
        { h: 'Fees and withdrawals', p: ['Withdrawal or transfer fees are an expense: record them as such so your profit is not inflated. Your mobile money balance is part of your cash, just like the till.'] },
        { h: 'With Kaislo', p: ['Kaislo offers the payment methods of your country (Wave, Orange Money, MTN, M-Pesa, card…). The evening accounts and the Excel report detail the money received by method. Kaislo never collects the money: it only keeps track of how your customers paid you.'] },
      ],
      faq: [
        ['Does Kaislo collect mobile money payments?', 'No. Your customers pay you as usual; Kaislo records the payment method for your accounts.'],
        ['How do I check my mobile money is right?', 'Compare the method’s total in your evening accounts with the credits in your app, allowing for fees.'],
      ],
    },
  },
  {
    cle: 'cout-plats',
    modele: 'ventes',
    metier: '/gestion-restaurant/',
    fr: {
      slug: 'calculer-le-cout-dun-plat-restaurant',
      seo: 'Calculer le coût d’un plat et le prix de la carte',
      titre: 'Restaurant : calculer le coût d’un plat et fixer le prix de la carte',
      court: 'Calculer le coût d’un plat',
      description: 'Comment calculer le coût de revient d’un plat, le coefficient multiplicateur et le prix de vente pour qu’un restaurant, un maquis ou un snack gagne vraiment de l’argent.',
      chapo: 'Un plat très demandé n’est pas forcément un plat rentable. Pour savoir ce que vous gagnez vraiment, il faut connaître le coût de chaque assiette, ingrédient par ingrédient.',
      sections: [
        { h: 'Le coût de revient d’un plat', p: ['Listez tous les ingrédients d’une portion avec leur quantité exacte, puis multipliez par le prix d’achat. Un poulet braisé avec 300 g de poulet à 2 500 le kilo, 100 g d’oignons et d’huile, et un peu de sauce coûte par exemple 1 100 de matière première.', 'Ajoutez la part des pertes (épluchures, cuisson, restes) : on compte souvent 5 à 10 % de plus.'] },
        { h: 'Le coefficient multiplicateur', p: ['En restauration, on obtient le prix de vente en multipliant le coût matière par un coefficient, souvent entre 2,5 et 3,5 pour couvrir le loyer, le personnel, le gaz et le bénéfice. Un plat à 1 100 de matière avec un coefficient de 3 se vend environ 3 300.', 'Le coefficient varie : plus faible pour une boisson ou un plat très cher à produire, plus élevé pour un plat simple et peu coûteux.'] },
        { h: 'Surveiller le pourcentage de matière', l: ['Coût matière ÷ prix de vente = pourcentage de matière.', 'Visez en général 25 à 35 % pour un restaurant, davantage pour un snack à forte rotation.', 'Recalculez dès qu’un prix d’achat monte (poulet, huile, riz).', 'Retirez ou repensez les plats qui dépassent largement le seuil.'] },
        { h: 'Les plats stars et les plats pièges', p: ['Regardez ensemble le nombre de ventes et la marge de chaque plat. Un plat vendu souvent avec une bonne marge est à mettre en avant ; un plat vendu souvent mais peu rentable doit voir son prix ou sa portion revus.'] },
        { h: 'Avec Kaislo', p: ['Kaislo enregistre chaque plat et boisson vendus, par table et par serveur, et les statistiques montrent ce qui se vend le plus. Avec le prix d’achat renseigné, vous suivez aussi la marge et les dépenses de la journée dans les comptes du soir.'] },
      ],
      faq: [
        ['Quel pourcentage de matière viser dans un restaurant ?', 'En général entre 25 et 35 % du prix de vente hors taxes, selon le type de restaurant et la place des boissons.'],
        ['Faut-il compter les boissons séparément ?', 'Oui : leur coût matière est plus faible, donc le coefficient est plus élevé. Suivez-les à part pour voir ce qu’elles rapportent.'],
      ],
    },
    en: {
      slug: 'calculate-restaurant-dish-cost',
      seo: 'Calculate dish cost and set your menu prices',
      titre: 'Restaurant: calculating the cost of a dish and pricing your menu',
      court: 'Calculating dish cost',
      description: 'How to calculate the cost of a dish, the markup multiplier and the selling price so that a restaurant, cafe or snack bar really makes money.',
      chapo: 'A dish customers order a lot is not necessarily a profitable dish. To know what you really earn, you need the cost of each plate, ingredient by ingredient.',
      sections: [
        { h: 'The cost of a dish', p: ['List every ingredient in one portion with its exact quantity, then multiply by the purchase price. A grilled chicken with 300 g of chicken at 2,500 per kilo, 100 g of onions and oil, and a little sauce costs, for example, 1,100 in raw materials.', 'Add a share for waste (peelings, cooking loss, leftovers): count 5 to 10% more.'] },
        { h: 'The markup multiplier', p: ['In catering, the selling price comes from multiplying the ingredient cost by a coefficient, often between 2.5 and 3.5, to cover rent, staff, gas and profit. A dish with 1,100 of ingredients and a coefficient of 3 sells for about 3,300.', 'The coefficient varies: lower for a drink or an expensive dish, higher for a simple, cheap one.'] },
        { h: 'Watch your food cost percentage', l: ['Ingredient cost ÷ selling price = food cost percentage.', 'Aim for 25 to 35% in a restaurant, more for a fast-turnover snack bar.', 'Recalculate whenever a purchase price rises (chicken, oil, rice).', 'Drop or rethink dishes that go well above the threshold.'] },
        { h: 'Star dishes and trap dishes', p: ['Look at how often each dish sells and its margin together. A frequent seller with a good margin should be promoted; a frequent seller with a thin margin needs a new price or portion.'] },
        { h: 'With Kaislo', p: ['Kaislo records every dish and drink sold, by table and by waiter, and the statistics show what sells most. With purchase prices entered, you also follow margin and the day’s expenses in the evening accounts.'] },
      ],
      faq: [
        ['What food cost percentage should a restaurant aim for?', 'Generally 25 to 35% of the selling price excluding tax, depending on the type of restaurant and how much drinks weigh.'],
        ['Should drinks be counted separately?', 'Yes: their ingredient cost is lower, so the coefficient is higher. Track them separately to see what they bring in.'],
      ],
    },
  },
  {
    cle: 'choisir-logiciel',
    modele: 'ventes',
    metier: '/gestion-boutique/',
    fr: {
      slug: 'choisir-un-logiciel-de-caisse-et-de-gestion',
      seo: 'Cahier, Excel ou logiciel de caisse : que choisir ?',
      titre: 'Cahier, Excel ou logiciel de caisse : comment choisir pour son commerce',
      court: 'Choisir un logiciel de caisse',
      description: 'Comparaison honnête entre cahier, tableur Excel et logiciel de caisse et de gestion pour un petit commerce : coût, erreurs, stock, crédit, ce qu’il faut vérifier avant de choisir.',
      chapo: 'Beaucoup de commerces démarrent avec un cahier, puis un fichier Excel. Ça marche tant que l’activité reste petite. Voici comment savoir quand passer à un logiciel, et quoi regarder avant de choisir.',
      sections: [
        { h: 'Le cahier : simple mais fragile', p: ['Le cahier ne coûte rien et tout le monde sait s’en servir. Mais il se perd, se mouille, ne calcule rien et ne permet pas de savoir vite ce qui reste en stock ni combien un client doit. Les erreurs d’addition passent inaperçues.'] },
        { h: 'Excel : puissant mais manuel', p: ['Un tableur permet de calculer, de trier et de garder un historique. En revanche, tout doit être saisi à la main après coup, le fichier n’existe que sur un appareil, deux personnes ne peuvent pas vendre en même temps, et une formule effacée par erreur fausse tous les chiffres.'] },
        { h: 'Le logiciel : la vente met tout à jour', p: ['Avec un logiciel de caisse et de gestion, chaque vente fait baisser le stock, alimente les comptes du soir et met à jour le carnet de crédit. Plusieurs vendeurs peuvent travailler en même temps, et les chiffres sont disponibles à tout moment.'] },
        { h: 'Les questions à poser avant de choisir', l: ['Fonctionne-t-il sans internet, avec envoi des données au retour du réseau ?', 'Sur quels appareils : téléphone, tablette, ordinateur ?', 'Gère-t-il le stock, le crédit client et les modes de paiement de mon pays ?', 'Les vendeurs ont-ils chacun un accès et des droits limités ?', 'Puis-je exporter mes données (Excel, PDF) et les récupérer si j’arrête ?', 'Quel est le prix réel, par mois, sans frais cachés ?'] },
        { h: 'Où se place Kaislo', p: ['Kaislo est pensé pour les restaurants, épiceries et boutiques : ventes, stock, inventaire, carnet de crédit, comptes du soir, vendeurs avec code PIN, rapports Excel et PDF. Il marche sans internet, sur téléphone, tablette ou ordinateur, avec un essai gratuit de 30 jours et un prix adapté à votre pays.'] },
      ],
      faq: [
        ['Quand passer d’Excel à un logiciel ?', 'Quand vous avez plusieurs vendeurs, un stock à suivre, des clients à crédit, ou que la saisie après coup vous prend du temps ou provoque des erreurs.'],
        ['Un logiciel de caisse oblige-t-il à acheter du matériel ?', 'Non. Kaislo marche sur un téléphone ou un ordinateur que vous avez déjà ; l’imprimante de tickets est facultative.'],
      ],
    },
    en: {
      slug: 'choosing-a-pos-and-management-software',
      seo: 'Notebook, Excel or POS software: which to choose?',
      titre: 'Notebook, Excel or POS software: how to choose for your business',
      court: 'Choosing POS software',
      description: 'An honest comparison of a notebook, an Excel spreadsheet and a point-of-sale and management software for a small business: cost, mistakes, stock, credit and what to check.',
      chapo: 'Many businesses start with a notebook, then an Excel file. It works while activity stays small. Here is how to know when to move to software, and what to look at before choosing.',
      sections: [
        { h: 'The notebook: simple but fragile', p: ['A notebook costs nothing and everyone can use it. But it gets lost or wet, calculates nothing and cannot tell you quickly what is left in stock or how much a customer owes. Addition mistakes go unnoticed.'] },
        { h: 'Excel: powerful but manual', p: ['A spreadsheet can calculate, sort and keep a history. But everything has to be typed in afterwards, the file lives on one device, two people cannot sell at once, and one accidentally deleted formula throws off every figure.'] },
        { h: 'Software: the sale updates everything', p: ['With point-of-sale and management software, each sale lowers stock, feeds the evening accounts and updates the credit book. Several sellers can work at once, and the figures are available at any time.'] },
        { h: 'Questions to ask before you choose', l: ['Does it work without internet and send data when the network returns?', 'On which devices: phone, tablet, computer?', 'Does it handle stock, customer credit and the payment methods of my country?', 'Does each seller have their own access and limited rights?', 'Can I export my data (Excel, PDF) and take it with me if I stop?', 'What is the real monthly price, with no hidden fees?'] },
        { h: 'Where Kaislo fits', p: ['Kaislo is designed for restaurants, grocery stores and shops: sales, stock, inventory, credit book, evening accounts, sellers with PIN codes, Excel and PDF reports. It works without internet, on phone, tablet or computer, with a 30-day free trial and a price suited to your country.'] },
      ],
      faq: [
        ['When should you move from Excel to software?', 'When you have several sellers, stock to track, customers on credit, or when typing things in afterwards takes time or causes mistakes.'],
        ['Does POS software force you to buy equipment?', 'No. Kaislo works on a phone or computer you already have; the receipt printer is optional.'],
      ],
    },
  },
  {
    cle: 'ouvrir-epicerie',
    modele: 'inventaire',
    metier: '/gestion-epicerie/',
    fr: {
      slug: 'ouvrir-une-epicerie-checklist',
      seo: 'Ouvrir une épicerie : la checklist pour bien démarrer',
      titre: 'Ouvrir une épicerie : la checklist pour bien démarrer',
      court: 'Ouvrir une épicerie',
      description: 'Les étapes pour ouvrir une épicerie ou une boutique de quartier : emplacement, budget de départ, premier stock, fournisseurs, prix, organisation et suivi des ventes.',
      chapo: 'Ouvrir une épicerie demande peu de matériel mais beaucoup d’organisation. Cette checklist vous aide à démarrer avec un stock adapté, des prix justes et un suivi simple dès le premier jour.',
      sections: [
        { h: 'Choisir l’emplacement et connaître sa clientèle', p: ['Observez le passage, les commerces voisins et ce que les habitants achètent le plus. Une épicerie réussit d’abord par sa proximité : les produits du quotidien (riz, huile, sucre, boissons, savon) doivent toujours être disponibles.'] },
        { h: 'Établir son budget de départ', l: ['Premier stock de marchandise.', 'Loyer ou caution, et licence ou autorisations locales.', 'Étagères, balance, réfrigérateur si besoin.', 'Réserve de trésorerie pour les premiers mois.', 'Un téléphone ou un ordinateur pour gérer les ventes.'] },
        { h: 'Constituer le premier stock', p: ['Commencez par les produits qui se vendent chaque jour, en petites quantités, plutôt qu’un gros stock de produits lents. Comparez au moins deux fournisseurs, négociez les prix à la quantité et notez chaque prix d’achat.'] },
        { h: 'Fixer ses prix et sa marge', p: ['Calculez votre marge sur chaque produit (voir notre guide sur la marge) et comparez avec les commerces voisins. Gardez une marge plus faible sur les produits très comparés (riz, sucre) et plus forte sur les produits d’appoint.'] },
        { h: 'Organiser le suivi dès le premier jour', p: ['Enregistrez chaque vente, chaque entrée de marchandise et chaque dépense, et faites vos comptes chaque soir. Avec Kaislo, vous ajoutez vos articles, suivez le stock, gérez le crédit des clients et voyez le bénéfice du jour sur votre téléphone.'] },
      ],
      faq: [
        ['Combien faut-il pour ouvrir une petite épicerie ?', 'Cela dépend du pays et de la taille ; prévoyez surtout le premier stock, le loyer et une réserve de trésorerie pour les premiers mois.'],
        ['Faut-il faire crédit aux clients dès le début ?', 'Mieux vaut commencer prudemment : crédit limité aux clients connus, avec un plafond et un délai clairs, noté dans un carnet.'],
      ],
    },
    en: {
      slug: 'opening-a-grocery-store-checklist',
      seo: 'Opening a grocery store: the checklist to start well',
      titre: 'Opening a grocery store: the checklist to start well',
      court: 'Opening a grocery store',
      description: 'The steps to open a grocery or neighbourhood shop: location, starting budget, first stock, suppliers, prices, organisation and sales tracking.',
      chapo: 'Opening a grocery store takes little equipment but a lot of organisation. This checklist helps you start with the right stock, fair prices and simple tracking from day one.',
      sections: [
        { h: 'Choose the location and know your customers', p: ['Watch foot traffic, neighbouring shops and what people buy most. A grocery store succeeds first through proximity: everyday products (rice, oil, sugar, drinks, soap) must always be available.'] },
        { h: 'Set your starting budget', l: ['First stock of goods.', 'Rent or deposit, and local licence or permits.', 'Shelves, scales, a fridge if needed.', 'A cash reserve for the first months.', 'A phone or computer to manage sales.'] },
        { h: 'Build the first stock', p: ['Start with products that sell every day, in small quantities, rather than a big stock of slow ones. Compare at least two suppliers, negotiate bulk prices and write down every purchase price.'] },
        { h: 'Set prices and margin', p: ['Calculate your margin on each product (see our margin guide) and compare with neighbouring shops. Keep a thinner margin on heavily compared products (rice, sugar) and a bigger one on convenience items.'] },
        { h: 'Organise tracking from day one', p: ['Record every sale, every delivery and every expense, and do your accounts each evening. With Kaislo you add your items, track stock, manage customer credit and see the day’s profit on your phone.'] },
      ],
      faq: [
        ['How much does it take to open a small grocery store?', 'It depends on the country and size; mostly plan for the first stock, rent and a cash reserve for the first months.'],
        ['Should you give customers credit from the start?', 'Better to begin carefully: credit limited to known customers, with a clear ceiling and deadline, written in a book.'],
      ],
    },
  },
  {
    cle: 'reappro',
    modele: 'inventaire',
    metier: '/gestion-stock/',
    fr: {
      slug: 'quand-recommander-ses-produits-seuil-de-stock',
      seo: 'Quand recommander ses produits : le seuil de stock',
      titre: 'Quand recommander ses produits : calculer son seuil de réapprovisionnement',
      court: 'Seuil de réapprovisionnement',
      description: 'Comment fixer un seuil d’alerte de stock par produit, calculer la quantité à commander et éviter à la fois les ruptures et le sur-stock dans votre commerce.',
      chapo: 'Une rupture fait perdre des ventes, un sur-stock immobilise votre argent. Le seuil de réapprovisionnement vous dit à quel moment précis il faut recommander.',
      sections: [
        { h: 'Connaître sa vitesse de vente', p: ['Pour chaque produit, notez combien vous en vendez en moyenne par jour ou par semaine. Un produit qui part à 10 unités par jour ne se gère pas comme un produit qui part à 10 par mois.'] },
        { h: 'Compter le délai de livraison', p: ['Combien de jours s’écoulent entre votre commande et la marchandise en rayon ? Si votre fournisseur met 3 jours, vous devez commander quand il vous reste au moins 3 jours de ventes.'] },
        { h: 'La formule du seuil', p: ['Seuil = ventes moyennes par jour × délai de livraison en jours + stock de sécurité. Pour un produit vendu 10 par jour avec 3 jours de délai et 10 unités de sécurité, le seuil est de 10 × 3 + 10 = 40 : à 40 unités, on commande.', 'Le stock de sécurité couvre les jours de forte vente ou un retard de livraison ; il est plus élevé pour les produits essentiels.'] },
        { h: 'Combien commander', l: ['Visez de quoi couvrir la période jusqu’à la prochaine livraison.', 'Tenez compte de la place disponible et de la date de péremption.', 'Profitez des prix par quantité seulement pour les produits qui se vendent vite.', 'Ne commandez jamais « au cas où » un produit qui dort.'] },
        { h: 'Automatiser avec les alertes Kaislo', p: ['Dans Kaislo, indiquez un seuil par article : dès que le stock passe sous ce seuil, l’article apparaît en alerte, et en rupture quand il tombe à zéro. Vous voyez d’un coup d’œil ce qu’il faut commander.'] },
      ],
      faq: [
        ['Qu’est-ce qu’un stock de sécurité ?', 'Une réserve supplémentaire gardée pour absorber une vente exceptionnelle ou un retard de livraison.'],
        ['Faut-il le même seuil pour tous les produits ?', 'Non : il dépend de la vitesse de vente et du délai de livraison de chaque produit.'],
      ],
    },
    en: {
      slug: 'when-to-reorder-stock-reorder-point',
      seo: 'When to reorder stock: how to set a reorder point',
      titre: 'When to reorder your products: calculating your reorder point',
      court: 'Reorder point',
      description: 'How to set a stock alert level per product, calculate the quantity to order and avoid both stock-outs and overstock in your shop.',
      chapo: 'A stock-out loses sales, overstock ties up your money. The reorder point tells you exactly when to order again.',
      sections: [
        { h: 'Know your sales speed', p: ['For each product, note how many you sell on average per day or week. A product that moves 10 units a day is not managed like one that moves 10 a month.'] },
        { h: 'Count the delivery time', p: ['How many days pass between your order and the goods being on the shelf? If your supplier takes 3 days, you must order when you have at least 3 days of sales left.'] },
        { h: 'The reorder point formula', p: ['Reorder point = average daily sales × delivery days + safety stock. For a product selling 10 a day with 3 days’ delivery and 10 units of safety stock, the point is 10 × 3 + 10 = 40: at 40 units, you order.', 'Safety stock covers busy days or a delivery delay; it is higher for essential products.'] },
        { h: 'How much to order', l: ['Aim to cover the period until the next delivery.', 'Consider available space and expiry dates.', 'Take bulk prices only for fast-selling products.', 'Never order “just in case” a product that sits still.'] },
        { h: 'Automate with Kaislo alerts', p: ['In Kaislo, set a threshold per item: as soon as stock drops below it, the item shows as low, and as out of stock when it reaches zero. You see at a glance what to order.'] },
      ],
      faq: [
        ['What is safety stock?', 'An extra reserve kept to absorb an exceptional sale or a delivery delay.'],
        ['Should every product have the same threshold?', 'No: it depends on each product’s sales speed and delivery time.'],
      ],
    },
  },
  {
    cle: 'vendeurs',
    modele: 'ventes',
    metier: '/gestion-boutique/',
    fr: {
      slug: 'gerer-ses-vendeurs-et-employes',
      seo: 'Gérer ses vendeurs : accès, droits et suivi des ventes',
      titre: 'Gérer ses vendeurs : accès, droits et suivi des ventes par employé',
      court: 'Gérer ses vendeurs',
      description: 'Comment organiser le travail de vos vendeurs : accès personnel, droits limités, ventes par employé, caisse du soir et prévention des erreurs ou des vols.',
      chapo: 'Quand vous n’êtes plus seul derrière le comptoir, la confiance ne suffit plus : il faut savoir qui a fait quoi. De bonnes règles protègent le commerce et les employés honnêtes.',
      sections: [
        { h: 'Un accès personnel pour chacun', p: ['Chaque vendeur doit avoir son propre compte avec son numéro et son code PIN. Ne partagez jamais votre code de gérant. Ainsi, chaque vente, remise et annulation est rattachée à une personne précise.'] },
        { h: 'Limiter les droits', l: ['Le vendeur enregistre les ventes et encaisse.', 'Seul le gérant (ou une personne de confiance) accorde des remises importantes.', 'Les annulations demandent un motif, voire le code du gérant.', 'La modification des prix et du stock est réservée à ceux qui en ont besoin.'] },
        { h: 'Suivre les ventes par employé', p: ['Comparez le chiffre d’affaires, le nombre de tickets et le panier moyen par vendeur. Ce n’est pas pour fliquer : cela repère les besoins de formation, les meilleurs vendeurs à récompenser et les écarts à expliquer.'] },
        { h: 'Faire les comptes du soir ensemble', p: ['Chaque soir, rapprochez l’argent compté du total attendu. Un écart récurrent sur un poste ou un vendeur doit être discuté calmement et rapidement, avec les chiffres sous les yeux.'] },
        { h: 'Avec Kaislo', p: ['Kaislo permet de créer des vendeurs avec code PIN, de leur donner des droits (produits, remises) et d’affecter un poste. Les annulations sont tracées avec un motif, et le rapport Excel ou PDF détaille les ventes par vendeur.'] },
      ],
      faq: [
        ['Pourquoi ne pas partager un seul compte ?', 'Parce qu’on ne peut plus savoir qui a fait une vente, une remise ou une annulation, ni corriger une erreur à la bonne personne.'],
        ['Un vendeur peut-il modifier les prix ?', 'Seulement si le gérant lui en donne le droit ; par défaut, la gestion des produits est réservée au gérant.'],
      ],
    },
    en: {
      slug: 'managing-your-sellers-and-staff',
      seo: 'Managing sellers: access, permissions and tracking',
      titre: 'Managing your sellers: access, permissions and sales by employee',
      court: 'Managing your sellers',
      description: 'How to organise your sellers’ work: personal access, limited permissions, sales per employee, evening cash-up and preventing mistakes or theft.',
      chapo: 'When you are no longer alone behind the counter, trust is not enough: you need to know who did what. Good rules protect the business and honest employees.',
      sections: [
        { h: 'Personal access for everyone', p: ['Each seller should have their own account with their own number and PIN. Never share your manager code. That way every sale, discount and cancellation is tied to a specific person.'] },
        { h: 'Limit permissions', l: ['The seller records sales and takes payment.', 'Only the manager (or a trusted person) gives big discounts.', 'Cancellations need a reason, even the manager’s code.', 'Changing prices and stock is reserved for those who need it.'] },
        { h: 'Track sales per employee', p: ['Compare revenue, number of tickets and average basket per seller. It is not about policing: it spots training needs, best sellers to reward and gaps to explain.'] },
        { h: 'Do the evening accounts together', p: ['Each evening, match counted cash against the expected total. A recurring gap on one till or seller should be discussed calmly and quickly, with the figures in front of you.'] },
        { h: 'With Kaislo', p: ['Kaislo lets you create sellers with PIN codes, give them permissions (products, discounts) and assign a till. Cancellations are traced with a reason, and the Excel or PDF report details sales per seller.'] },
      ],
      faq: [
        ['Why not share a single account?', 'Because you can no longer tell who made a sale, a discount or a cancellation, nor correct a mistake with the right person.'],
        ['Can a seller change prices?', 'Only if the manager grants the right; by default, product management is reserved for the manager.'],
      ],
    },
  },
  {
    cle: 'comptabilite',
    modele: 'ventes',
    metier: '/gestion-epicerie/',
    fr: {
      slug: 'tenir-la-comptabilite-simple-de-son-commerce',
      seo: 'Comptabilité simple d’un petit commerce : les bases',
      titre: 'Tenir la comptabilité simple de son petit commerce',
      court: 'Comptabilité simple d’un commerce',
      description: 'Les bases d’une comptabilité simple pour un petit commerce : ventes, dépenses, bénéfice, séparer argent perso et argent du commerce, et préparer les documents pour le comptable.',
      chapo: 'Pas besoin d’être comptable pour savoir si votre commerce gagne de l’argent. Quelques habitudes simples suffisent pour y voir clair et préparer vos documents.',
      sections: [
        { h: 'Séparer l’argent du commerce et l’argent personnel', p: ['C’est la règle la plus importante. Fixez-vous un salaire que vous prélevez à date fixe, et ne puisez pas dans la caisse pour vos dépenses personnelles : sinon, vous ne saurez jamais si le commerce est rentable.'] },
        { h: 'Noter chaque jour ventes et dépenses', l: ['Total vendu, par mode de paiement (espèces, mobile money, carte, crédit).', 'Achats de marchandise.', 'Charges : loyer, électricité, transport, salaires, téléphone.', 'Tout ce que vous prélevez pour vous.'] },
        { h: 'Calculer le bénéfice', p: ['Bénéfice = ventes − coût des marchandises vendues − charges. Faites ce calcul chaque mois. Un chiffre d’affaires qui monte ne veut pas dire un bénéfice qui monte : regardez la marge et les dépenses.'] },
        { h: 'Garder les justificatifs', p: ['Conservez factures d’achat, reçus de paiement et relevés de mobile money, classés par mois. Ils servent pour votre comptable, pour une demande de prêt et en cas de contrôle.'] },
        { h: 'Préparer le travail du comptable avec Kaislo', p: ['Chaque mois, exportez le rapport Excel ou PDF : ventes, articles, dépenses, crédits dus et stock. Votre comptable reçoit un classeur propre avec des vrais nombres, sans ressaisie.'] },
      ],
      faq: [
        ['Quelle différence entre chiffre d’affaires et bénéfice ?', 'Le chiffre d’affaires est tout ce que vous vendez ; le bénéfice est ce qu’il reste après avoir retiré le coût des marchandises et les charges.'],
        ['Que donner à mon comptable ?', 'Le rapport mensuel de ventes et de dépenses, les factures d’achat, les relevés de mobile money et la liste des crédits clients.'],
      ],
    },
    en: {
      slug: 'simple-bookkeeping-for-a-small-business',
      seo: 'Simple bookkeeping for a small shop: where to start',
      titre: 'Simple bookkeeping for your small business',
      court: 'Simple bookkeeping',
      description: 'The basics of simple bookkeeping for a small business: sales, expenses, profit, separating personal and business money and preparing documents for your accountant.',
      chapo: 'You do not need to be an accountant to know whether your business makes money. A few simple habits are enough to see clearly and prepare your documents.',
      sections: [
        { h: 'Separate business money from personal money', p: ['This is the most important rule. Set yourself a salary that you take on a fixed date, and do not dip into the till for personal spending: otherwise you will never know if the business is profitable.'] },
        { h: 'Record sales and expenses every day', l: ['Total sold, by payment method (cash, mobile money, card, credit).', 'Purchases of goods.', 'Costs: rent, electricity, transport, salaries, phone.', 'Anything you take out for yourself.'] },
        { h: 'Work out your profit', p: ['Profit = sales − cost of goods sold − costs. Do this calculation every month. Rising revenue does not mean rising profit: look at margin and expenses.'] },
        { h: 'Keep your supporting documents', p: ['Keep purchase invoices, payment receipts and mobile money statements, filed by month. They serve your accountant, a loan application and any inspection.'] },
        { h: 'Prepare your accountant’s work with Kaislo', p: ['Each month, export the Excel or PDF report: sales, items, expenses, credit owed and stock. Your accountant receives a clean workbook with real numbers, no retyping.'] },
      ],
      faq: [
        ['What is the difference between revenue and profit?', 'Revenue is everything you sell; profit is what is left after removing the cost of goods and costs.'],
        ['What should I give my accountant?', 'The monthly sales and expenses report, purchase invoices, mobile money statements and the list of customer credit.'],
      ],
    },
  },
];

// Guides généraux, puis un guide par pays
export const GUIDES = [...GUIDES_BASE, ...GUIDES_PAYS];

export const MODELES = {
  inventaire: {
    fr: { fichier: 'modele-inventaire-stock.xlsx', nom: 'Modèle Excel d’inventaire de stock (gratuit)' },
    en: { fichier: 'stock-inventory-template.xlsx', nom: 'Stock inventory Excel template (free)' },
  },
  ventes: {
    fr: { fichier: 'modele-suivi-ventes-quotidien.xlsx', nom: 'Modèle Excel de suivi des ventes et dépenses (gratuit)' },
    en: { fichier: 'daily-sales-tracker-template.xlsx', nom: 'Daily sales and expenses Excel template (free)' },
  },
};

export const adresseGuide = (g, lang) => (lang === 'en' ? '/en/guides/' : '/guides/') + g[lang].slug + '/';
export const guideParSlug = (slug, lang) => GUIDES.find((g) => g[lang].slug === slug);
